from setuptools import find_packages, setup

setup(
    name="efficientvit",
    packages=find_packages(),
    install_requires=[
        "torch",
        "torchvision",
        "torchmetrics",
        "numpy",
        "timm",
        "einops",
        "opencv-python",
        "tqdm",
        "torchprofile",
        "scipy",
        "torch-fidelity",
        "diffusers",
        "omegaconf",
        "ipdb",
        "wandb",
        "matplotlib",
        "huggingface-hub",
        "transformers",
        "onnx",
        "onnxsim",
        "onnxruntime",
        "pycocotools",
        "lvis",
        "scikit-image",
        "tinyneuralnetwork @ git+https://github.com/alibaba/TinyNeuralNetwork.git",
        "segment_anything @ git+https://github.com/facebookresearch/segment-anything.git",
    ],
)
